<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{b66c7c96-5039-4af5-8cda-935a9b086c6f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	//fbLogHandler : FB_LogHandler;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
PRG_Gas_Injection();

//fbLogHandler();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>