<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{b66c7c96-5039-4af5-8cda-935a9b086c6f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    fbLogHandler : FB_LogHandler;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fbLogHandler();

PRG_ECAT_CHECK();

PRG_GAUGES();

PRG_VALVES();

PRG_TURBO_PUMPS();

PRG_HV_ILK();

PRG_COIL_PS_ILK();

PRG_TC();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>