<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="POU_Interlock" Id="{a30357a6-8d74-4b6d-bda7-5c5ec5f69b13}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM POU_Interlock
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//Interlock 

//]]></ST>
    </Implementation>
    <LineIds Name="POU_Interlock">
      <LineId Id="3" Count="2" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>