<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_HV_ILK" Id="{d0f59b88-3cfc-41d8-b70c-ef6b66a977a9}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_HV_ILK
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*High Voltage Saftey Loop*)
GVL_PLC_Interface.bHVSafteyLoopEnable := (GVL_VAC_GAUGES.stDREAM_MC_GAUGE.rPRESS <= fHighVoltageMinPressure AND GVL_VAC_GAUGES.stDREAM_MC_GAUGE.xPRESS_OK) AND
                                         (DREAM_DP1_PTM_01.iq_stPTM.eState = E_PumpState.pumpRUNNING AND
                                          DREAM_DP2_PTM_01.iq_stPTM.eState = E_PumpState.pumpRUNNING AND
                                          DREAM_DP3_PTM_01.iq_stPTM.eState = E_PumpState.pumpRUNNING AND
                                          DREAM_MC_PTM_01.iq_stPTM.eState = E_PumpState.pumpRUNNING AND
                                          DREAM_MC_PTM_02.iq_stPTM.eState = E_PumpState.pumpRUNNING AND
                                          DREAM_CAT1_PTM_01.iq_stPTM.eState = E_PumpState.pumpRUNNING AND
                                          DREAM_CAT2_PTM_01.iq_stPTM.eState = E_PumpState.pumpRUNNING AND
                                          DREAM_ROUGH2_PTM_01.iq_stPTM.eState = E_PumpState.pumpRUNNING AND
                                          DREAM_ROUGH2_PTM_02.iq_stPTM.eState = E_PumpState.pumpRUNNING);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>