<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_TC" Id="{af381e65-1cb1-40ba-a67a-42436983bb1f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TC
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Measure Thercmocouples
TC_01();
TC_02();
TC_03();
TC_04();
TC_05();
TC_06();
TC_07();
TC_08();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>