<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_COIL_PS_ILK" Id="{3fe79328-964f-4827-83b5-a95ad08eb1c0}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_COIL_PS_ILK
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*Interlock logic for Coil PS based on reading from Flow meter*)
fbCoilPSFlowMeter();
bCoilPS_ILK := fbCoilPSFlowMeter.fReal > 2.5; //If flow meter reading is above XX is ok to turn ON output of the Coil PS. Units are lpm]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>